---
title: "bible project"
author: "kmr and mlc"
format: html
editor: visual
---

```{r libraries, message=FALSE}
library(tidyverse)
library(beepr) 
```

```{r load-data, message=FALSE}
personrelation <- read_csv('relationship.csv')
# all relational data on people
# can create a book variable from the reference column

person_info <- read_csv('person.csv')
## list of all people mentioned in the bible in order
# gender, name frequency (may be suspect, matches the id differentiator?), tribe
# shares person_id with personrelation

personlabel <- read_csv('label.csv')
# labels and label types
# shares person_label_id with personverse, unclear to Michael what the two numbers represent

personverse <- read_csv('personverse.csv')
# shares person_label_id with personlabel

book_info <- read_csv('bibledata_book.csv')
# number of chapters and verses

verses <- read.csv('alamopolyglot.csv')
# all verses of the Bible

## NOTES
# Not sure if there's a way to get a single person_id
# all person ones have a person_id column
```

```{r joining-data}
left_join(personrelation, person_info |> select(person_id, sex, tribe), 
          by = join_by(person_id_1 = person_id))


```

```{r most-common}
personrelation |> 
  group_by(relationship_type) |> 
  summarize(count = n()) |> 
  ungroup() |> 
  arrange(desc(count))
```

```{r multiple-relationships}
multiple_relations <- personrelation |> 
  mutate(relationship_type = as_factor(relationship_type)) |> 
  group_by(person_id_1, person_id_2) |> 
  summarize(n = n(), .groups = 'keep') |>
  ungroup() |> 
  filter(n > 1) |> 
  right_join(personrelation, by = join_by(person_id_1, person_id_2)) |> 
  filter(n > 1) |> 
  select(person_id_1, relationship_type, person_id_2, everything(), -n) 

multiple_relations

# Most common
multiple_relations |> 
  group_by(relationship_type) |> 
  summarize(n = n()) |> 
  ungroup() |> 
  arrange(desc(n))

# these don't seem too clean 😬
```

```{r relationships-wide, warning=FALSE}
personrelation |> 
  select(person_id_1, person_id_2, relationship_type) |> 
  pivot_wider(names_from = relationship_type, 
              values_from = relationship_type) |> 
  unnest() |> 
  mutate(across(!starts_with("person_id"), ~if_else(!is.na(.), 1, 0)), 
         n_relates = rowSums(across(where(is.numeric)), na.rm = TRUE)) |> 
  select(person_id_1, person_id_2, n_relates, everything()) |> 
  arrange(desc(n_relates))
```

```{r family-identification}
family_types 
c('son', 
  'father', 
  'mother', 
  'daughter', 
  'brother', 
  'sister', 
  )

personrelation |> 
  select(relationship_type) |> 
  filter()
```

```{r explore-book-length}
book_info |> 
  ggplot(aes(x = chapter_count)) + geom_histogram() + theme_minimal()

book_info |> 
  ggplot(aes(x = verse_count)) + geom_histogram() + theme_minimal()

book_info |> 
  ggplot(aes(x = christian_sequence, 
             y = chapter_count)) +
  #geom_line() + 
  geom_text(aes(label = book_name, 
                color = verse_count)) + 
  theme_minimal()
```

```{r}
person_info |> 
  ggplot(aes(x = name_instance)) + geom_histogram()
```
